"""
重新生成 requirements-docker.txt，过滤掉与 cu126 torch 冲突的包。

问题：poetry export 会把 CPU torch 的传递依赖（nvidia-*、triton、cuda-bindings 等）
     也导出来，但 Docker 构建用的是 cu126 torch wheel（自带 CUDA 12.6 库），
     这些包的 CUDA 12.8 版本会与 torch 自带的 12.6 库冲突。

用法：
  poetry run python scripts/export_docker_requirements.py
"""
import subprocess
import sys
import re

# 与 cu126 torch 冲突的包前缀/名称
EXCLUDED_PACKAGES = [
    "nvidia-",           # CUDA 12.8 runtime libs (cublas, cudnn, etc.)
    "triton",            # GPU compiler, bundled in cu126 wheel
    "cuda-bindings",     # CUDA Python bindings, not needed with cu126
    "cuda-pathfinder",   # CUDA discovery, not needed with cu126
]


def should_exclude(line: str) -> bool:
    """检查一行是否应该被排除"""
    line = line.strip()
    if not line or line.startswith("#") or line.startswith("--"):
        return False
    # 提取包名（在 == 之前）
    match = re.match(r'^([a-zA-Z0-9_-]+)', line)
    if not match:
        return False
    pkg_name = match.group(1).lower()
    for excluded in EXCLUDED_PACKAGES:
        if pkg_name.startswith(excluded) or pkg_name == excluded.rstrip("-"):
            return True
    return False


def main():
    print("正在通过 poetry export 生成 requirements...")

    result = subprocess.run(
        ["poetry", "export", "--without-hashes", "--only", "main", "-f", "requirements.txt"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"poetry export 失败:\n{result.stderr}")
        sys.exit(1)

    lines = result.stdout.splitlines()
    filtered = []
    excluded_count = 0

    for line in lines:
        if should_exclude(line):
            excluded_count += 1
            pkg = line.strip().split("==")[0]
            print(f"  ❌ 排除: {pkg}")
        elif line.strip().startswith("--index-url"):
            # 跳过 index-url，由 Dockerfile 的 PIP_INDEX_URL 控制
            print(f"  ⏭️  跳过: --index-url (由 Dockerfile 控制)")
        else:
            filtered.append(line)

    # 写入文件，添加头部注释
    header = [
        "# Auto-generated by scripts/export_docker_requirements.py",
        "# DO NOT EDIT MANUALLY - run the script to regenerate",
        "#",
        "# nvidia-*, triton, cuda-bindings, cuda-pathfinder are excluded because",
        "# Docker builds use cu126 torch wheel which bundles its own CUDA 12.6 libs.",
        "# index-url is controlled by Dockerfile's PIP_INDEX_URL, not hardcoded here.",
        "",
    ]

    with open("requirements-docker.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(header))
        f.write("\n".join(filtered))
        if filtered and not filtered[-1].endswith("\n"):
            f.write("\n")

    print(f"\n✅ 已生成 requirements-docker.txt")
    print(f"   总行数: {len(filtered)}")
    print(f"   排除包: {excluded_count}")


if __name__ == "__main__":
    main()
